import type { RequirementModule, RequirementQuestion, RequirementRisk, TestPoint } from '@/pages/RequirementAnalysis/types';

export const modules: RequirementModule[] = [
  {
    id: 'module-login',
    name: '统一登录与权限',
    owner: '产品中台',
    description: '覆盖账号密码登录、单点登录、角色权限校验与异常拦截。',
    coverage: 86,
    testPointCount: 8,
    questionCount: 2,
    riskCount: 2,
    status: 'analyzed',
    complexity: 'high',
    tags: ['认证', '权限', 'SSO'],
  },
  {
    id: 'module-requirement',
    name: '需求输入与解析',
    owner: 'AI 工作台',
    description: '支持多格式需求录入、结构化解析、关键信息抽取与版本追踪。',
    coverage: 78,
    testPointCount: 6,
    questionCount: 3,
    riskCount: 1,
    status: 'pending',
    complexity: 'medium',
    tags: ['需求解析', 'NLP', '版本'],
  },
  {
    id: 'module-case',
    name: '用例生成与编辑',
    owner: '测试效能',
    description: '基于测试点生成用例，支持人工编辑、批量确认和导出。',
    coverage: 91,
    testPointCount: 9,
    questionCount: 1,
    riskCount: 2,
    status: 'confirmed',
    complexity: 'medium',
    tags: ['用例', '导出', '批量'],
  },
];

export const requirementQuestions: RequirementQuestion[] = [
  {
    id: 'q-001',
    moduleId: 'module-login',
    title: '连续失败锁定策略是否按租户独立配置？',
    detail: '需求仅描述失败 5 次锁定账号，但未说明不同租户是否允许自定义阈值。',
    priority: 'high',
    status: 'open',
    assignee: '产品经理',
    suggestion: '补充租户级安全策略配置说明，并定义默认阈值。',
  },
  {
    id: 'q-002',
    moduleId: 'module-requirement',
    title: '上传需求附件的大小和格式限制不明确',
    detail: '当前仅说明支持 Word、PDF，未描述最大文件大小、失败提示和重试方式。',
    priority: 'medium',
    status: 'open',
    assignee: '业务分析师',
    suggestion: '确认格式白名单、大小上限和上传失败兜底交互。',
  },
  {
    id: 'q-003',
    moduleId: 'module-case',
    title: '导出模板是否需要保留历史版本？',
    detail: '导出模板可能被团队配置覆盖，需要明确历史用例是否仍按旧模板导出。',
    priority: 'low',
    status: 'answered',
    assignee: '测试负责人',
    suggestion: '已确认按导出时最新模板生成，不保留模板快照。',
  },
];

export const risks: RequirementRisk[] = [
  {
    id: 'r-001',
    moduleId: 'module-login',
    title: '权限绕过风险',
    description: '角色权限变更后，前端缓存和后端鉴权可能存在短暂不一致。',
    level: 'high',
    category: 'security',
    mitigation: '增加 token 刷新、接口鉴权和权限变更后的缓存失效测试。',
  },
  {
    id: 'r-002',
    moduleId: 'module-requirement',
    title: '解析结果不可追溯',
    description: 'AI 解析后的字段若缺少来源定位，会影响用户校验和问题复盘。',
    level: 'medium',
    category: 'business',
    mitigation: '保留原文引用片段和解析置信度，测试低置信度提示。',
  },
  {
    id: 'r-003',
    moduleId: 'module-case',
    title: '批量确认误操作',
    description: '批量确认可能将尚未评审的测试点直接进入用例生成链路。',
    level: 'medium',
    category: 'business',
    mitigation: '增加二次确认、筛选范围提示和操作审计。',
  },
];

export const testPoints: TestPoint[] = [
  {
    id: 'tp-001',
    moduleId: 'module-login',
    title: '账号密码登录成功后进入默认工作台',
    precondition: '用户账号有效且具备工作台访问权限。',
    steps: ['输入正确账号密码', '点击登录', '等待系统完成鉴权跳转'],
    expectedResult: '登录成功并进入工作台总览，侧边栏展示当前角色可访问菜单。',
    priority: 'P0',
    type: 'functional',
    status: 'confirmed',
    relatedRiskIds: ['r-001'],
    source: '统一登录需求第 2.1 节',
  },
  {
    id: 'tp-002',
    moduleId: 'module-login',
    title: '连续输错密码触发账号锁定提示',
    precondition: '账号处于未锁定状态。',
    steps: ['连续 5 次输入错误密码', '第 6 次尝试登录'],
    expectedResult: '系统阻止登录并展示锁定原因、解锁方式和剩余时间。',
    priority: 'P0',
    type: 'exception',
    status: 'generated',
    relatedRiskIds: ['r-001'],
    source: '安全策略需求第 3.4 节',
  },
  {
    id: 'tp-003',
    moduleId: 'module-requirement',
    title: '上传 PDF 需求后生成结构化需求摘要',
    precondition: '用户已进入需求输入与解析页面。',
    steps: ['上传包含业务流程的 PDF', '点击开始解析', '查看解析结果'],
    expectedResult: '系统生成模块、流程、验收标准和待确认字段，且保留来源片段。',
    priority: 'P1',
    type: 'functional',
    status: 'draft',
    relatedRiskIds: ['r-002'],
    source: '需求解析用户故事 US-03',
  },
  {
    id: 'tp-004',
    moduleId: 'module-case',
    title: '批量确认筛选后的测试点',
    precondition: '列表中存在多个生成态测试点。',
    steps: ['按优先级筛选测试点', '勾选全部结果', '点击确认测试点'],
    expectedResult: '仅当前筛选范围内的测试点变更为已确认，并记录操作人。',
    priority: 'P1',
    type: 'functional',
    status: 'generated',
    relatedRiskIds: ['r-003'],
    source: '用例生成需求第 4.2 节',
  },
];
