export type CasePriority = 'P0' | 'P1' | 'P2';
export type CaseType = '功能正向' | '异常流程' | '边界值' | '权限安全' | '兼容回归' | '性能并发';

export interface GeneratedTestCase {
  id: string;
  caseNo: string;
  module: string;
  title: string;
  priority: CasePriority;
  caseType: CaseType;
  automated: boolean;
  precondition: string;
  steps: string;
  testData: string;
  expectedResult: string;
  remark: string;
  updateTime: string;
}

export const caseGenerationMock: GeneratedTestCase[] = [
  {
    id: 'case-001',
    caseNo: 'AI-TC-20260602-001',
    module: '优惠券领取',
    title: '验证库存充足时用户领取成功',
    priority: 'P0',
    caseType: '功能正向',
    automated: true,
    precondition: '活动已发布，优惠券库存充足，用户未领取过该券。',
    steps: '1. 登录有效用户账号\n2. 进入优惠券活动页\n3. 点击立即领取\n4. 查询用户券包与库存变化',
    testData: '用户：normal_user_001；库存：100；活动状态：进行中',
    expectedResult: '领取请求成功，用户券包新增该优惠券，库存扣减 1，页面展示领取成功提示。',
    remark: '核心领取链路，建议纳入冒烟自动化。',
    updateTime: '2026-06-02 09:10:00',
  },
  {
    id: 'case-002',
    caseNo: 'AI-TC-20260602-002',
    module: '优惠券领取',
    title: '验证 600 用户并发领取 30 份库存不能超发',
    priority: 'P0',
    caseType: '性能并发',
    automated: true,
    precondition: '活动已发布，优惠券库存固定为 30，准备 600 个未领取用户。',
    steps: '1. 构造 600 个用户并发领取请求\n2. 同时触发领取接口\n3. 汇总成功领取数量\n4. 查询最终库存与发券记录',
    testData: '并发用户数：600；库存：30；压测窗口：5 秒',
    expectedResult: '成功领取数量不超过 30，库存不为负，失败用户收到库存不足提示，无重复发券。',
    remark: '关注分布式锁、库存扣减事务和幂等控制。',
    updateTime: '2026-06-02 09:12:00',
  },
  {
    id: 'case-003',
    caseNo: 'AI-TC-20260602-003',
    module: '优惠券领取',
    title: '验证库存为 0 时领取失败并提示库存不足',
    priority: 'P0',
    caseType: '边界值',
    automated: true,
    precondition: '活动进行中，优惠券库存为 0，用户未领取过。',
    steps: '1. 登录用户账号\n2. 打开活动页\n3. 点击立即领取',
    testData: '库存：0；用户：normal_user_002',
    expectedResult: '领取失败，不生成用户优惠券记录，页面提示库存不足。',
    remark: '库存边界场景。',
    updateTime: '2026-06-02 09:15:00',
  },
  {
    id: 'case-004',
    caseNo: 'AI-TC-20260602-004',
    module: '优惠券领取',
    title: '验证用户重复领取同一优惠券时被拦截',
    priority: 'P1',
    caseType: '异常流程',
    automated: true,
    precondition: '用户已领取过当前优惠券，活动仍在有效期内。',
    steps: '1. 使用已领取用户登录\n2. 进入活动页\n3. 再次点击立即领取\n4. 查询发券记录',
    testData: '用户：claimed_user_001；优惠券：coupon_618_a',
    expectedResult: '系统拒绝重复领取，不新增发券记录，并提示用户已领取。',
    remark: '需要校验幂等键与用户领取记录。',
    updateTime: '2026-06-02 09:18:00',
  },
  {
    id: 'case-005',
    caseNo: 'AI-TC-20260602-005',
    module: '活动规则',
    title: '验证活动未开始时领取入口置灰',
    priority: 'P1',
    caseType: '异常流程',
    automated: false,
    precondition: '活动配置为未来开始时间，页面可访问。',
    steps: '1. 打开活动页\n2. 查看领取按钮状态\n3. 尝试点击领取按钮',
    testData: '开始时间：当前时间 + 1 天',
    expectedResult: '按钮置灰不可点击，展示活动未开始文案，不触发领取接口。',
    remark: '适合 UI 回归检查。',
    updateTime: '2026-06-02 09:20:00',
  },
  {
    id: 'case-006',
    caseNo: 'AI-TC-20260602-006',
    module: '活动规则',
    title: '验证活动结束后用户不能领取',
    priority: 'P1',
    caseType: '异常流程',
    automated: true,
    precondition: '活动结束时间早于当前时间，用户未领取过。',
    steps: '1. 登录用户\n2. 打开已结束活动页\n3. 点击领取或调用领取接口',
    testData: '结束时间：当前时间 - 1 小时',
    expectedResult: '领取失败，接口返回活动已结束，页面同步展示结束状态。',
    remark: '覆盖前端与接口双重校验。',
    updateTime: '2026-06-02 09:22:00',
  },
  {
    id: 'case-007',
    caseNo: 'AI-TC-20260602-007',
    module: '用户资格',
    title: '验证非会员用户领取会员专享券失败',
    priority: 'P1',
    caseType: '权限安全',
    automated: true,
    precondition: '活动限制会员领取，当前用户为非会员。',
    steps: '1. 使用非会员账号登录\n2. 进入会员专享券活动页\n3. 点击立即领取',
    testData: '用户等级：普通用户；券类型：会员专享券',
    expectedResult: '领取失败，提示不满足会员资格，库存不扣减。',
    remark: '资格校验需在服务端执行。',
    updateTime: '2026-06-02 09:25:00',
  },
  {
    id: 'case-008',
    caseNo: 'AI-TC-20260602-008',
    module: '用户资格',
    title: '验证黑名单用户无法领取优惠券',
    priority: 'P0',
    caseType: '权限安全',
    automated: true,
    precondition: '用户命中风控黑名单，活动库存充足。',
    steps: '1. 使用黑名单用户登录\n2. 调用领取接口\n3. 查询风控日志与发券记录',
    testData: '用户：risk_user_001；风控标签：blacklist',
    expectedResult: '领取被拒绝，生成风控拦截日志，不产生发券记录。',
    remark: '安全高优先级场景。',
    updateTime: '2026-06-02 09:28:00',
  },
  {
    id: 'case-009',
    caseNo: 'AI-TC-20260602-009',
    module: '接口幂等',
    title: '验证同一请求幂等键重复提交只发放一次',
    priority: 'P0',
    caseType: '异常流程',
    automated: true,
    precondition: '用户未领取，客户端携带固定幂等键。',
    steps: '1. 构造相同幂等键的两次领取请求\n2. 快速连续提交\n3. 查询发券记录和接口响应',
    testData: '幂等键：idem-618-001；请求次数：2',
    expectedResult: '最多生成一条发券记录，两次响应保持一致或第二次返回已处理。',
    remark: '关注重试与网络抖动场景。',
    updateTime: '2026-06-02 09:30:00',
  },
  {
    id: 'case-010',
    caseNo: 'AI-TC-20260602-010',
    module: '数据校验',
    title: '验证缺失活动 ID 时领取接口返回参数错误',
    priority: 'P2',
    caseType: '边界值',
    automated: true,
    precondition: '用户登录态有效，接口请求体不传活动 ID。',
    steps: '1. 构造缺失活动 ID 的领取请求\n2. 发送请求\n3. 检查响应码和错误信息',
    testData: 'activityId：空；couponId：coupon_618_a',
    expectedResult: '接口返回参数错误，不扣减库存，不产生发券记录。',
    remark: '基础参数校验。',
    updateTime: '2026-06-02 09:32:00',
  },
  {
    id: 'case-011',
    caseNo: 'AI-TC-20260602-011',
    module: '页面兼容',
    title: '验证移动端页面领取按钮与结果弹窗展示正常',
    priority: 'P2',
    caseType: '兼容回归',
    automated: false,
    precondition: '移动端浏览器打开活动页，活动库存充足。',
    steps: '1. 使用移动端视口打开活动页\n2. 点击领取按钮\n3. 查看成功弹窗与券包入口',
    testData: '设备：iPhone 15；浏览器：Safari',
    expectedResult: '按钮位置、弹窗文案和券包入口展示正常，无遮挡或错位。',
    remark: '人工验收移动端布局。',
    updateTime: '2026-06-02 09:35:00',
  },
  {
    id: 'case-012',
    caseNo: 'AI-TC-20260602-012',
    module: '消息通知',
    title: '验证领取成功后发送站内信通知',
    priority: 'P2',
    caseType: '功能正向',
    automated: false,
    precondition: '用户开启站内信通知，活动库存充足。',
    steps: '1. 用户领取优惠券成功\n2. 进入消息中心\n3. 查看站内信内容',
    testData: '通知模板：coupon_claim_success',
    expectedResult: '消息中心新增领取成功通知，通知内容包含优惠券名称和有效期。',
    remark: '可与消息服务联调验证。',
    updateTime: '2026-06-02 09:38:00',
  },
];
